- hosts: webserver
  gather_facts: no
  vars:
    users:
      - jane
      - sansa
      - robert
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: charlie
        state: present
        key: "{{ lookup('file', './files/id_rsa_ansible.pub') }}"
        path: 