- name: Установка Git
  hosts: webserver
  tasks:
    - name: install git server
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes # выполняет команду apt-get update для того, чтобы обновить информацию о пакетах в индексе. 
      become: yes # в плейбуке Ansible указывает на выполнение задачи с привилегиями суперпользователя для доступа к необходимым ресурсам или операциям на целевой машине.
      tags: git
    
    - name: Install Node.js and Npm
      ansible.builtin.apt:
        name: 
          - nodejs
          - npm
        state: present
        update_cache: yes
      become: yes
      tags: node

    - name: add users
      user:
        name: "{{ item }}"
        state: present
      loop:
        - arya
        - sansa
        - tirion
      tags: users
# Добавить обновление пакетов, уставновку git, node или nvm. Бонусом nginx. Это будет уже полезно. Можно добавить команды в Makefile.
