- name: Nginx Playbook
  hosts: webserver
  vars:
    nginx_config_dir: /etc/nginx
    default_nginx_html_dir: /usr/share/nginx/html
    nginx_port: 8080
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes
      tags: nginx
    
    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf
        dest: "{{ nginx_config_dir }}/nginx.conf"
      notify:
        - restart nginx
      become: yes

    - name: update nginx html
      ansible.builtin.template:
        src: files/index.html
        dest: "{{ default_nginx_html_dir }}/index.html"
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

