- name: Setup
  hosts: webserver
  tasks:
    - name: install git server
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes # выполняет команду apt-get update для того, чтобы обновить информацию о пакетах в индексе. 
      become: yes # в плейбуке Ansible указывает на выполнение задачи с привилегиями суперпользователя для доступа к необходимым ресурсам или операциям на целевой машине.
      tags: git
    
    - name: Install Node.js and Npm
      ansible.builtin.apt:
        name: 
          - nodejs
          - npm
        state: latest
        update_cache: yes
      become: yes
      tags: node

    - name: add users
      user:
        name: "{{ item }}"
        state: present
      loop:
        - arya
        - sansa
        - tirion
      tags: users
